
[build]
  command = "npm install --legacy-peer-deps && npm run build --configuration=production"
  publish = "dist" 
  node_version = "16.16.0"


[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
